exports.appName="graphing"
exports.localization = {};
exports.localization.appName ={
  "en_US": "Graphing Calc",
  "ar": "Graphing Calc",
  "bg": "Графика",
  "bs": "Graphing Calc",
  "ca": "Gràfics",
  "cs": "Grafy",
  "da": "Graftegner",
  "de": "Grafikrechner",
  "el": "Γράφημα",
  "es": "Graficadora",
  "fa": "Graphing Calc",
  "fi": "Kuvaajat",
  "fr": "Grapheur",
  "hr": "Grafički kalkulator",
  "hu": "Graphing Calc",
  "it": "Calc Grafica",
  "ja": "関数グラフ",
  "kk": "Graphing Calc",
  "ko": "그래픽 계산기",
  "lt": "Graphing Calc",
  "mn": "График тооцоолуур",
  "nl": "Grafieken",
  "no": "Graphing Calc",
  "no_NO": "Grafisk kalkulator",
  "no_NO_NY": "Grafteikning",
  "pl": "Wykresy",
  "pt": "Graphing Calc",
  "ro": "Graphing Calc",
  "ru": "Graphing Calc",
  "sk": "Graphing Calc",
  "sl": "Grafično računalo",
  "sv": "Grafräknare",
  "tr": "Grafik Hesap",
  "uk": "Графіки",
  "vi": "Graphing Calc",
  "zh": "Graphing Calc",
  "zh_CN": "图形计算器",
  "zh_TW": "繪圖計算"};
